version: '3.7'
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginxasp
    ports:
      - "80:80"
    links:
      - "web"
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aspnginx    

    